/*Program to display simple messages and values on an LCD screen
Adapted from publically available GITHUB program for an arduino
01/11/23
Version 3
FURTHER MODIFIED BY SAM HOBERN
*/

#include "mbed.h"
#include "TextLCD_CC.h"

DigitalIn SW4(PB_1, PullUp);

int main() 
{
    // Characters can be generated by various online tools
    // 5x8 array.
    char moon[] = {0x07, 0x0E,0x1C,0x1C,0x1C,0x1C,0x0E,0x07};
    int moon_character = 0;
    TextLCD mainLCD(D9, D8, D0, D1, D2, D3, TextLCD::LCD20x4);
    
    char swordoneA[8] { 0x00, 0x00, 0x08, 0x0F, 0x0F, 0x08, 0x00, 0x00 };
    char swordoneB[8] { 0x0C, 0x0C, 0x0F, 0x1F, 0x1F, 0x0F, 0x0C, 0x0C };
    char swordoneC[8] { 0x00, 0x00, 0x1F, 0x1F, 0x1F, 0x1F, 0x00, 0x00 };
    char swordoneD[8] { 0x00, 0x00, 0x1C, 0x1F, 0x1F, 0x1C, 0x00, 0x00 };

    char Ocustom[] = {0x0E,0x1F,0x1B,0x1B,0x1B,0x1B,0x1F,0x0E};
    char Rcustom[] = {0x1E,0x1B,0x1B,0x1F,0x1E,0x1B,0x1B,0x1B};  
    char Icustom[] = {0x1F,0x1F,0x0E,0x0E,0x0E,0x0E,0x1F,0x1F};
    char Ncustom[] = {0x1F,0x1F,0x1F,0x1B,0x1B,0x1B,0x1B,0x1B};

    

    mainLCD.writeCustomCharacter(swordoneA, 1); // bottom
    mainLCD.writeCustomCharacter(swordoneB, 2);
    mainLCD.writeCustomCharacter(swordoneC, 3);
    mainLCD.writeCustomCharacter(swordoneD, 4); // tip of sword
    
    mainLCD.locate(6,2);
    mainLCD.printf("Welcome!\n");
    thread_sleep_for(2000);
    
    mainLCD.cls();
    mainLCD.locate(6,0);
    mainLCD.printf("Welcome!\n");
    mainLCD.locate(4,2);
    mainLCD.printf("Press button");
    mainLCD.locate(4,3);
    mainLCD.printf("to continue...");
    mainLCD.locate(8,1);
    mainLCD.printf("%c%c%c%c",0,1,2,3);

    while(true){
   
        mainLCD.writeCustomCharacter(Ocustom, 5); 
        mainLCD.writeCustomCharacter(Rcustom, 6);
        mainLCD.writeCustomCharacter(Icustom, 7);
        mainLCD.writeCustomCharacter(Ncustom, 8);
    
        if (SW4 == false) {
      
        mainLCD.cls();
             
        mainLCD.locate(2,1);
        mainLCD.printf("introducing...");
   
        thread_sleep_for(1000);

        mainLCD.cls();

        mainLCD.locate(8,0);
        mainLCD.printf("The");
        mainLCD.locate(0,1);
        thread_sleep_for(500);
        mainLCD.printf("DUNGEONS INTERACTIVE");
        thread_sleep_for(500);
        mainLCD.locate(7,2);
        mainLCD.printf("%c%c%c%c%c", 4,5,6,4,7);
        
        }
    }
        
}
